apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: login-app-secrets
  namespace: login-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/login-app/mysql/host"
        objectType: "ssmparameter"
      - objectName: "/login-app/mysql/database"
        objectType: "ssmparameter"
      - objectName: "/login-app/mysql/user"
        objectType: "ssmparameter"
      - objectName: "/login-app/mysql/password"
        objectType: "ssmparameter"
