apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  namespace: login-app
  labels:
    app: login-app
spec:
  selector:
    app: login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
